<?php
/** @var $this BasicRender */
/** @var $articles ArticleDTO[] */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>List of articles</title>
</head>
<body>
<ul>
    <?php foreach ( $articles as $article ): ?>
        <li>
            <a href="<?= $article->link ?>"><?= $this->escape( $article->title ) ?></a>
        </li>
    <?php endforeach ?>
</ul>
</body>
</html>